tools:
    external_code_coverage: true
    php_code_sniffer: true
    sensiolabs_security_checker: true
    php_pdepend: true
    php_mess_detector: true
    php_loc: true
    php_cpd: true
    php_analyzer: true